name: ${project.artifactId}
main: ${main.class}
version: ${project.version}
api-version: 1.13
author: kangarko
softdepend: [AuthMe, BossShop, BlueShop, BungeeChatAPI, DiscordSRV, Factions, Feudal, Essentials, ChestShop, LegacyFactions, NashornPlus, LuckPerms, MVdWPlaceholderAPI, Multiverse-Core, Nicky, PlaceholderAPI, PowerNBT, ProtocolLib, Shop, ShopGUIPlus, SignShop, SimpleClans, Towny, TownyChat, Vault, WorldEdit]
#
# The commands are built at runtime so you can change them easily within the settings.
# Do not change anything in here, you will break the plugin and get no support.
#
commands: 
permissions: 
  confiscate.log.exempt:
    default: false
    description: Player will be ignored from logging.
  confiscate.commandspy.exempt:
    default: false
    description: The commands player execute will not be logged and you will not be notified about them.